// <auto-generated />
using System;
using Aireq.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Aireq.Api.Migrations
{
    [DbContext(typeof(AireqDbContext))]
    [Migration("20260518162232_AddPasswordHashToUser")]
    partial class AddPasswordHashToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aireq.Api.Data.Entities.Consultant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Headline")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("headline");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("location");

                    b.Property<decimal?>("RateTargetUsdHourly")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("rate_target_usd_hourly");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkAuth")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("work_auth");

                    b.HasKey("Id")
                        .HasName("pk_consultants");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_consultants_tenant_id");

                    b.ToTable("consultants");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.ConsultantSkill", b =>
                {
                    b.Property<Guid>("ConsultantId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultant_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<string>("Evidence")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("evidence");

                    b.Property<decimal?>("Years")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("years");

                    b.HasKey("ConsultantId", "SkillId")
                        .HasName("pk_consultant_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_consultant_skills_skill_id");

                    b.ToTable("consultant_skills");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Escalation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_escalations");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("ix_escalations_resolved_at");

                    b.HasIndex("MatchId", "CreatedAt")
                        .HasDatabaseName("ix_escalations_match_id_created_at");

                    b.ToTable("escalations");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("description");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("SourceExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_external_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_jobs_is_active");

                    b.HasIndex("PostedAt")
                        .HasDatabaseName("ix_jobs_posted_at");

                    b.HasIndex("Source", "SourceExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_jobs_source_source_external_id");

                    b.ToTable("jobs");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsultantId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("ReasoningJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("reasoning_json");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_matches_job_id");

                    b.HasIndex("ConsultantId", "JobId")
                        .IsUnique()
                        .HasDatabaseName("ix_matches_consultant_id_job_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_matches_tenant_id_status");

                    b.ToTable("matches");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiModel")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ai_model");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("body");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<bool>("GeneratedByAi")
                        .HasColumnType("boolean")
                        .HasColumnName("generated_by_ai");

                    b.Property<string>("PromptHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("prompt_hash");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ThreadId", "SentAt")
                        .HasDatabaseName("ix_messages_thread_id_sent_at");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.RecruiterThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastInboundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_inbound_at");

                    b.Property<DateTimeOffset?>("LastOutboundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_outbound_at");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("RecruiterEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("recruiter_email");

                    b.Property<string>("RecruiterName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recruiter_name");

                    b.Property<bool>("RequiresHuman")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_human");

                    b.Property<string>("Sentiment")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sentiment");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_recruiter_threads");

                    b.HasIndex("RecruiterEmail")
                        .HasDatabaseName("ix_recruiter_threads_recruiter_email");

                    b.HasIndex("MatchId", "RecruiterEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_recruiter_threads_match_id_recruiter_email");

                    b.ToTable("recruiter_threads");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsultantId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("OriginalFilename")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_filename");

                    b.Property<string>("ParsedJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_json");

                    b.Property<string>("SourceBlobUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_blob_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_resumes");

                    b.HasIndex("ConsultantId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_resumes_consultant_id_version");

                    b.ToTable("resumes");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_slug");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("ResponsePayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload_json");

                    b.Property<string>("ResponseStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("response_status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_submissions_match_id");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("ix_submissions_submitted_at");

                    b.ToTable("submissions");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.TailoredResume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AtsScore")
                        .HasColumnType("integer")
                        .HasColumnName("ats_score");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blob_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiffJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("diff_json");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tailored_resumes");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_tailored_resumes_match_id");

                    b.ToTable("tailored_resumes");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("plan");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_name");

                    b.ToTable("tenants");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_users_tenant_id_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Consultant", b =>
                {
                    b.HasOne("Aireq.Api.Data.Entities.Tenant", "Tenant")
                        .WithMany("Consultants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consultants_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.ConsultantSkill", b =>
                {
                    b.HasOne("Aireq.Api.Data.Entities.Consultant", "Consultant")
                        .WithMany("Skills")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consultant_skills_consultants_consultant_id");

                    b.HasOne("Aireq.Api.Data.Entities.Skill", "Skill")
                        .WithMany("Consultants")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consultant_skills_skills_skill_id");

                    b.Navigation("Consultant");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Escalation", b =>
                {
                    b.HasOne("Aireq.Api.Data.Entities.Match", "Match")
                        .WithMany("Escalations")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escalations_matches_match_id");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Match", b =>
                {
                    b.HasOne("Aireq.Api.Data.Entities.Consultant", "Consultant")
                        .WithMany("Matches")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_consultants_consultant_id");

                    b.HasOne("Aireq.Api.Data.Entities.Job", "Job")
                        .WithMany("Matches")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_jobs_job_id");

                    b.HasOne("Aireq.Api.Data.Entities.Tenant", "Tenant")
                        .WithMany("Matches")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_tenants_tenant_id");

                    b.Navigation("Consultant");

                    b.Navigation("Job");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Message", b =>
                {
                    b.HasOne("Aireq.Api.Data.Entities.RecruiterThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_recruiter_threads_thread_id");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.RecruiterThread", b =>
                {
                    b.HasOne("Aireq.Api.Data.Entities.Match", "Match")
                        .WithMany("Threads")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recruiter_threads_matches_match_id");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Resume", b =>
                {
                    b.HasOne("Aireq.Api.Data.Entities.Consultant", "Consultant")
                        .WithMany("Resumes")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resumes_consultants_consultant_id");

                    b.Navigation("Consultant");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Submission", b =>
                {
                    b.HasOne("Aireq.Api.Data.Entities.Match", "Match")
                        .WithMany("Submissions")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_matches_match_id");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.TailoredResume", b =>
                {
                    b.HasOne("Aireq.Api.Data.Entities.Match", "Match")
                        .WithMany("TailoredResumes")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tailored_resumes_matches_match_id");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.User", b =>
                {
                    b.HasOne("Aireq.Api.Data.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Consultant", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Resumes");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Job", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Match", b =>
                {
                    b.Navigation("Escalations");

                    b.Navigation("Submissions");

                    b.Navigation("TailoredResumes");

                    b.Navigation("Threads");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.RecruiterThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Skill", b =>
                {
                    b.Navigation("Consultants");
                });

            modelBuilder.Entity("Aireq.Api.Data.Entities.Tenant", b =>
                {
                    b.Navigation("Consultants");

                    b.Navigation("Matches");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
